lead regoin role command bug fix
Progressive-Victory/crm-bot pull request #76
Opened 2023-06-17 18:42 UTC by bowenjw

Missed reference to states in lead region role command added the following helper functions to state.ts

```ts
function isMemberStateLead(member: GuildMember): Promise<boolean>

function isStateLeadRole(role: Role): boolean

function memberStates(member: GuildMember): Collection<string, Role>
```

2023-06-17 22:38 UTC, Lewdcario commented on src/structures/states.ts
> +	const role = await member.guild.roles.fetch(stateLeadRoleID);
No need to use a promise here - roles should be cached

2023-06-18 00:14 UTC, Lewdcario requested changes

2023-06-18 00:14 UTC, Lewdcario commented on src/structures/sme.ts
> +	return SMERoles;
I would prefer a smaller version of this:
```ts
return member.roles.filter(id => SMERoleIDs.includes(id));
```

2023-06-18 00:14 UTC, Lewdcario commented on src/structures/states.ts
> +	if (!role) throw Error('Missing Valid STATE_LEAD_ROLE_ID in .env');
Misleading error, we should check for the env being present first, and then return false if the role isn't present in their list of roles

2023-06-18 00:33 UTC, bowenjw commented on src/structures/states.ts
> +	if (!role) throw Error('Missing Valid STATE_LEAD_ROLE_ID in .env');
132 gets the role from the guild
so it check both if the env is present and if the role is in the guild

2023-06-18 00:41 UTC, bowenjw commented on src/structures/sme.ts
> +	return SMERoles;
sorry this was not meant to included this change in the this fix some of my code leaked over on accident. I will make the change

2023-06-18 02:08 UTC, Lewdcario commented on src/structures/states.ts
> +	if (!role) throw Error('inalid Role ID please check STATE_LEAD_ROLE_ID in .env');
Invalid

2023-06-18 02:19 UTC, Lewdcario commented on src/commands/chat/execution/lead/region/role.ts
> +	if (!memberStates(stateLead).some((role) => memberStates(target).has(role.id))) {
![image](https://github.com/Progressive-Victory/crm-bot/assets/11844002/8850195b-ae03-4413-bc53-9887e9495a6c)

2023-06-18 02:26 UTC, Lewdcario commented on src/commands/chat/execution/lead/region/role.ts
> +		args: { role: regionLeadRole.toString(), tag: target.user.tag }
![image](https://github.com/Progressive-Victory/crm-bot/assets/11844002/fd73d4f5-bfa3-43e1-ae65-4efe6a7a6412)

2023-06-18 02:30 UTC, Lewdcario approved these changes

2023-06-18 02:30 UTC, merged