VC Join Request Command
Progressive-Victory/crm-bot pull request #89
Opened 2023-09-03 02:30 UTC by bowenjw

## Refactor
 - Added `dockerfile` and `docker-compose.yaml` ( to running with docker desktop)
 - Updated scripts in pakage.json to work with `dockerfile`
 - Updated module files to latest version

# VC Join Request Command
The new command `/vc request-join`, is meant to allow the automatons  movement of members to full channels with out moderator intervention. The command has one non-required options `channel`, witch may be used to target a destination channel. If no channel is given the command will try and use the channel it was run from.

Requirements to send request and approved:
- Be in a VC to send request
- Be in VC to approve Request
- Request must be approved in 10 or it will need to be sent again
- Only one user in the targeted VC needs to approve of the join request

2023-09-03 02:34 UTC, bowenjw commented
the PR is missing some comments will add tomorrow also for some reason lint did not run successfully IDK why. will look in to it

2023-09-06 20:51 UTC, Lewdcario requested changes

2023-09-06 20:51 UTC, Lewdcario commented on src/Client/interactionCreate.ts
> +					// Else the interactions is replied too
too -> to

2023-09-06 20:51 UTC, Lewdcario commented on locales/en-US/vc.ftl
> +move-successful = Request Approved
Newline

2023-09-06 20:51 UTC, Lewdcario commented on .github/workflows/lint.yml
> +              run: yarn install --silent
This should contain `--frozen-lockfile`

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		interaction
Use await instead of then

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +	requester.voice.setChannel(interaction.channel as VoiceChannel);
await

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		.then(() => deleteMessage(interaction));
await instead of then

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		interaction
await instead of then

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		.then(() => deleteMessage(interaction));
On second thought, these feel redundant, so maybe combining the logic might be good

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		interaction.message.delete();
await

2023-09-06 20:51 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		interaction.reply({
await

2023-09-06 20:51 UTC, Lewdcario commented on src/commands/chat/execution/vc/join.ts
> +	interaction.member.voice.setChannel(channel);
await

2023-09-06 22:15 UTC, bowenjw commented
@Lewdcario all requested changes made

2023-09-07 21:16 UTC, Lewdcario requested changes
I marked some comments as unresolved as the issue persisted

2023-09-07 21:16 UTC, Lewdcario commented on dockerfile
> +CMD [ "yarn", "start" ]
Newline

2023-09-07 21:16 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		updateInteraction(interaction, 'request-exspired', { time: interaction.createdAt.toDiscordString('R') });
await

2023-09-07 21:16 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +		updateInteraction(interaction, 'requester-not-in-old-channel', { member: interaction.member.toString() });
await

2023-09-07 21:16 UTC, Lewdcario commented on src/interactions/buttons/vc.ts
> +	updateInteraction(interaction, 'move-successful', { member: interaction.member.toString() });
await

2023-09-07 22:32 UTC, Lewdcario approved these changes

2023-09-07 22:33 UTC, merged