Scoped Events
Progressive-Victory/crm-bot pull request #90
Opened 2023-09-10 02:19 UTC by bowenjw

This PR add one  Sub command group to the `lead` command
To-dos:
[ ] add comments

## Sub-commands
### Create
create a event and temporary channels

Options:
- name - name of the event
- description - the description of the event
- date - time when the event will start
### Update
Update the permissions overrides on the event channels

Options:
- channel - the text channel associated with the event

## Other functions
- On end or cancellation of a event it is check if event channels should be deleted
- On update of an the name on an event the associated channels names will update
- On the deletion of a channel associated with an event the other channel will be deleted and the event will canceled

2023-09-18 20:22 UTC, Lewdcario requested changes

2023-09-18 20:22 UTC, Lewdcario commented on src/events/guildScheduledEventDelete.ts
> +		channel.delete('Event Deleted');
I suggest a Promise.all operation here and then putting the channel deletes there. They need to be awaited otherwise

2023-09-18 20:22 UTC, Lewdcario commented on src/events/guildScheduledEventDelete.ts
> +		eventLogChannel.send({
await

2023-09-18 20:22 UTC, Lewdcario commented on src/interactions/modals/event-create.ts
> +	});
Are we checking for channel create permissions at the beginning of event creation flow?

2023-09-18 20:22 UTC, Lewdcario commented on src/interactions/modals/event-create.ts
> +	});
I think manage role is also needed to manage channel permissions

2023-09-18 20:22 UTC, Lewdcario commented on src/interactions/select_menus/vc.ts
> +	});
I don't recommend using forEach here as it doesn't do what you think it does, nothing's being waited for here, use a `for...of` loop

2023-09-18 20:22 UTC, Lewdcario commented on src/util/channel/index.ts
> +	return new AttachmentBuilder(messageArryToBuffer(await fetchAllMessages(channel)), { name: `${channel.name.replace(' ', '-').toLowerCase()}-message-log.txt}` });
Are we checking that the bot has permissions to retrieve message history in the beginning of event flow

2023-09-18 20:22 UTC, Lewdcario commented on src/util/channel/log-all-messages.ts
> +	let message = (await channel.messages.fetch({ limit: 1, cache: false })).first();
Perm check

2023-09-18 20:22 UTC, Lewdcario commented on src/util/channel/log-all-messages.ts
> +	let message = (await channel.messages.fetch({ limit: 1, cache: false })).first();
I also recommend using a recursive function and the DIscord.js collection, but this is an opinionated thing, if this works, that's also fine.

2023-09-19 01:09 UTC, Lewdcario requested changes
I'll test it tomorrow to see if there's other things to point out
Thanks for the help!

2023-09-19 01:09 UTC, Lewdcario commented on src/interactions/select_menus/vc.ts
> +		interaction.reply({
await

2023-09-19 01:09 UTC, Lewdcario commented on src/interactions/select_menus/vc.ts
> +		// send sucsses messages
success

2023-09-19 01:29 UTC, bowenjw commented on src/interactions/select_menus/vc.ts
> +		interaction.reply({
it is in the Promise.all

2023-09-21 17:16 UTC, Lewdcario approved these changes

2023-09-21 17:25 UTC, merged